### ISSUE TITLE
TODOs Roadmap

### ISSUE THREAD

**Issue by pirate** [Monadical-SAS/zervice.zup#1]
- [ ] implement redis db to store run outputs 
- [ ] implement `cron` foreground worker with dramatic/apscheduler?
- [ ] improve UI styling
- [ ] move `/tasks` -> `/` and `/` -> `/hosts`
- [ ] implement `[includes]` config option
- [ ] implement push-notification/email/sms/zulip? based alerting
- [ ] implement docker container healthchecks multi-task
- [ ] implement supervisord container healthchecks multi-task
- [ ] implement systemd healthchecks multi-task
